---
name: Mockingbird
version: 1.0
main: ethaniccc\Mockingbird\Mockingbird
api: [3.0.0]

permissions:
  mockingbird:
    children:
      mockingbird.alerts:
        description:
        default: op
      mockingbird.bypass:
        description:
        default: op
      mockingbird.debug:
        description:
        default: op
      mockingbird.logs:
        description:
        default: op
...
