---
name: Mockingbird
version: 2.5.2
main: ethaniccc\Mockingbird\Mockingbird
api: 3.19.0
mcpe-protocol: [431, 440, 448]

permissions:
  mockingbird:
    children:
      mockingbird.alerts:
        description: Get Mockingbird anti-cheat alerts.
        default: op
      mockingbird.bypass:
        description: Allows the user to bypass Mockingbird's detections
        default: op
      mockingbird.debug:
        description: Get Mockingbird debug messages in-game
        default: op
      mockingbird.logs:
        description: Get the anti-cheat logs of a player
        default: op
...
